apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: coursemapper-webserver-

vars:
- fieldref: {}
  name: MONGODB_SERVICE
  objref:
    apiVersion: v1
    kind: Service
    name: mongodb
labels:
- includeSelectors: true
  pairs:
    app: coursemapper-webserver

configMapGenerator:
- name: ingress
  literals:
  - host=coursemapper.soco.inko.cloud

secretGenerator:
- name: webserver
  literals:
  - COOKIE_SECRET=secret
  - JWT_SECRET=secret
  - PASS=adminpassword

images:
- name: mongo
  newTag: "6.0"
- name: socialcomputing/coursemapper-webserver-webapp
  newTag: latest
- name: socialcomputing/coursemapper-webserver-webserver
  newTag: latest

replacements:
- source:
    kind: ConfigMap
    name: ingress
    fieldPath: data.host
  targets:
  - select:
      kind: Ingress
      name: proxy
    fieldPaths:
    - spec.rules.0.host
- source:
    kind: ConfigMap
    name: ingress
    fieldPath: data.host
  targets:
  - select:
      kind: Ingress
      name: proxy
    fieldPaths:
    - spec.tls.0.hosts.0

resources:
- ingress.yaml
- webapp/deployment.yaml
- webapp/service.yaml
- webserver/deployment.yaml
- webserver/service.yaml
- webserver/pvc.yaml
- mongodb/deployment.yaml
- mongodb/service.yaml
- mongodb/pvc.yaml
