changelog:
  exclude:
    labels:
    - ignore-for-release

  categories:
    - title: 🎉 Exciting New Features
      labels:
      - enhancement

    - title: 🧰 Fixes
      labels:
      - bug

    - title: 🔗 Webapp Dependencies
      labels:
      - dependencies
      exclude:
        labels:
        - coursemapper-kg
        - webserver
        - proxy
        - github_actions

    - title: 🔗 Webserver Dependencies
      labels:
      - dependencies
      exclude:
        labels:
        - coursemapper-kg
        - webapp
        - proxy
        - github_actions

    - title: 🔗 coursemapper-kg Dependencies
      labels:
      - dependencies
      exclude:
        labels:
        - webapp
        - webserver
        - github_actions
        - proxy

    - title: 🔗 CI/CD Dependencies
      labels:
      - dependencies
      exclude:
        labels:
        - coursemapper-kg
        - webapp
        - webserver
        - proxy

    - title: 🔗 Other Dependencies
      labels:
      - dependencies
      exclude:
        labels:
        - coursemapper-kg
        - webapp
        - webserver
        - github_actions

    - title: 🎨 Other Changes
      labels:
      - '*'
      exclude:
        labels:
        - enhancement
        - bug
        - dependencies
