apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: webserver-

resources:
- neo4j
- redis
- web

secretGenerator:
- name: webserver
  literals:
  - COOKIE_SECRET=secret
  - JWT_SECRET=secret
  - PASS=adminpassword
  - NEO4J_USER=neo4j
  - NEO4J_PASSWORD=password
  - REDIS_DATABASE=0
  - REDIS_PASSWORD=""
