services:
  coursemapper-kg:
    image: coursemapper-webserver-coursemapper-kg-web

  wp-pg:
    ports:
    - 5432:5432

  proxy:
    image: coursemapper-webserver-proxy

  webapp:
    image: coursemapper-webserver-webapp
    build:
      dockerfile: dev.Dockerfile
    ports:
    - 4200:4200
    volumes:
    - ./webapp:/app

  webserver:
    image: coursemapper-webserver-webserver
    build:
      dockerfile: dev.Dockerfile
    ports:
    - 8080:8080
    volumes:
    - ./webserver:/app
    - ./webserver/public/uploads:/app/public/uploads
