apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: coursemapper-kg-

resources:
- concept-map
- recommendation
- pgadmin
- wp-pg

secretGenerator:
- name: coursemapper-kg-wp-pg
  literals:
  - ACCESS_KEY_ID=ACCESS_KEY_ID
  - SECRET_ACCESS_KEY=SECRET_ACCESS_KEY
