apiVersion: apps/v1
kind: Deployment
metadata:
  name: concept-map
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - name: worker
        image: coursemapper-kg-concept-map
        env:
        - name: NEO4J_URI
          value: "bolt://$(NEO4J_SERVICE):7687"
        - name: NEO4J_USER
          value: neo4j
        - name: NEO4J_PASSWORD
          value: password
        - name: REDIS_HOST
          value: $(REDIS_SERVICE)
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        - name: REDIS_PASSWORD
          value: ""
        - name: PIPELINES
          value: concept-map,modify-graph,expand-material
        - name: WIKIPEDIA_DATABASE_CONNECTION_STRING
          value: postgres://postgres:password@$(WP_PG_SERVICE):5432
        - name: WIKIPEDIA_FALLBACK
          value: "false"
        resources:
          requests:
            cpu: 100m
            memory: 4Gi
          limits:
            cpu: 1
            memory: 12Gi
