apiVersion: v1
kind: Service
metadata:
  name: neo4j
spec:
  ports:
  - name: http
    protocol: TCP
    port: 7474
    targetPort: 7474
  - name: bolt
    protocol: TCP
    port: 7687
    targetPort: 7687
