class Cache:
    def __init__(self):
        ...

    def get(self, key: str) -> str | None:
        ...

    def set(self, key: str, value: str) -> bool | None:
        ...

    def hset(self, key: str, field: str, value: str) -> int:
        ...

    def hget(self, key: str, field: str) -> str | None:
        ...

    def delete(self, key: str) -> int:
        ...

    def flush(self) -> bool:
        ...
