apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: web
        image: webserver
        ports:
        - containerPort: 8080
          name: http
        startupProbe:
          httpGet:
            path: /api/healthz
            port: 8080
        livenessProbe:
          httpGet:
            path: /api/healthz
            port: 8080
          timeoutSeconds: 30
          failureThreshold: 5
          periodSeconds: 60
        env:
        - name: PORT
          value: "8080"
        - name: MONGO_DB
          value: "mongodb://$(MONGODB_SERVICE):27017/coursemapper"
        - name: NEO4J_URI
          value: "bolt://$(NEO4J_SERVICE):7687"
        - name: REDIS_HOST
          value: $(REDIS_SERVICE)
        - name: REDIS_PORT
          value: "6379"
        - name: MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "0"
              resource: limits.memory
        - name: NODE_OPTIONS
          value: "--max-old-space-size=$(MEMORY_LIMIT)"
        envFrom:
        - secretRef:
            name: webserver
        volumeMounts:
        - mountPath: /app/public/uploads/images
          name: webserver-uploads
          subPath: images
        - mountPath: /app/public/uploads/pdfs
          name: webserver-uploads
          subPath: pdfs
        - mountPath: /app/public/uploads/videos
          name: webserver-uploads
          subPath: videos
        resources:
          requests:
            memory: 0.8Gi
            cpu: 100m
          limits:
            memory: 2Gi
            cpu: "1"
            ephemeral-storage: 1Gi
      volumes:
      - name: webserver-uploads
        persistentVolumeClaim:
          claimName: webserver-uploads
