apiVersion: v1
kind: Service
metadata:
  name: web
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: sticky
spec:
  selector:
    component: web
  ports:
  - port: 81
    targetPort: http
