apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: webserver-redis

resources:
- deployment.yaml
- service.yaml

vars:
- name: REDIS_SERVICE
  objref:
    apiVersion: v1
    kind: Service
    name: redis
  fieldref: {}
