apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sc

patches:
- target:
    kind: Deployment
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/imagePullPolicy
      value: Never

resources:
- ../base
- ingress.yaml
