apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: coursemapper-kg-pgadmin

resources:
- deployment.yaml
- ingress.yaml
- service.yaml

configMapGenerator:
- name: config
  files:
  - servers.json
  - passwords.txt
