services:
  webserver:
    image: ${IMAGE_NAME_PREFIX:-socialcomputing/}coursemapper-webserver-webserver:${IMAGE_TAG:-latest}
    build: .
    environment:
      PORT: 8080
      COOKIE_SECRET: secret
      JWT_SECRET: secret
      EMAIL: admin@soco.com
      PASS: adminpassword
      WEBAPP_URL: http://localhost:8000
      MONGO_DB: mongodb://mongo:27017/coursemapper
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
      REDIS_HOST: webserver-redis
      REDIS_PORT: 6379
      REDIS_DATABASE: 0
      REDIS_PASSWORD: ""
    volumes:
    - webserver-uploads-pdfs:/app/public/uploads/pdfs
    - webserver-uploads-videos:/app/public/uploads/videos
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      neo4j:
        condition: service_healthy

volumes:
  webserver-uploads-pdfs:
  webserver-uploads-videos:
