services:
  coursemapper-kg-worker-recommendation:
    platform: linux/x86_64
    image: ${IMAGE_NAME_PREFIX:-socialcomputing/}coursemapper-webserver-coursemapper-kg-recommendation:${IMAGE_TAG:-latest}
    build: .
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_PASSWORD: 
      PIPELINES: concept-recommendation,resource-recommendation
    depends_on:
      neo4j:
        condition: service_healthy
      redis:
        condition: service_healthy
